function coloc

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% "The preRC protein ORCA/LRWD1 Organizes Heterochromatin by 
% Assembling Histone H3 Lysine 9 Methyltransferases on Chromatin"
% 
% Sumanprava Giri, Vasudha Aggarwal, Julien Pontis, Zhen Shen , 
% Arindam Chakraborty, Abid Khan, Craig Mizzen, Kannanganattu V. 
% Prasanth, Slimane Ait-Si-Ali, Prof. Taekjip Ha, Supriya Prasanth
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Given the files for 2 channels, calulating the percentage overlap.
% Overlap over 2 pixel distances is diaplyed.
% Input file will include the [x,y] coordinates values for all 
% identified single-molecules. In our case, this file is .pks
% which is generated by using IDL scripts (available at 
% bio.physics.illinois.edu)
% Example of a .pks file
%     Mol.No      X            Y
%       1      13.5000      11.0000      
%       2      14.5000      448.000    
%       3      15.0000      153.000      
%       4      18.5000      228.000   
%       5      21.0000      320.000      
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all
close all;
fclose('all');

%% ====================== Input directory ============================
% Acquire two images (one 488 excitation, one 568 excitation of the 
% same imaging area. Input the path of the directory containing the 
% pairs of overlapping images.

pth=input('Directory [default=C:\User\New Folder]  ');
	if isempty(pth)
   	pth='C:\User\New Folder';
	end
cd(pth);

%% ====================== Enter the file names ========================
filename1=input('Index # of 568 file [default=1] ')
filename2=input('Index # of 488 file [default=2] ')

if isempty(filename1)
    filename1=1;
end

if isempty(filename2)
   	filename2=2;
end

filename1=num2str(filename1);
filename2=num2str(filename2);
  
d1 = load([filename1 '.pks']);
d2 = load ([filename2 '.pks']);

%% ====================== count overlap ==============================
% Overlapping distance is 2 pixel (~300 nm) and can be changed depending
% on the microscope resolution and magnification

len1 = length (d1); % Calculate number of single mCherry spots
len2 = length (d2); % Calculate number of single YFP spots

overlap2 = 0;
for i = 1:len1
    for j = 1:len2
        if abs(d1(i, 2) - d2 (j, 2)) <= 2.0  % 2 pixel in X coordinate
            if abs(d1(i, 3) - d2(j, 3)) <= 2.0 % 2 pixel in Y coordinate
                overlap2 = overlap2 + 1;
            end   
         end
     end
end

disp('Total number of mCherry points =  '); disp(len1);
disp('Total number of YFP points =  '); disp(len2);
disp('Number of overlapping points =  '); disp(overlap2);
disp('Percentage overlap over total YFP = '); disp(overlap2*100/len2);  
end
